/*    Copyright 2012 SequoiaDB Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// This Header File is automatically generated, you MUST NOT modify this file anyway!
// On the contrary, you can modify the xml file "sequoiadb/misc/rcgen/rclist.xml" if necessary!

#include "ossErr.h"

const CHAR* getErrDesp ( INT32 errCode )
{
    INT32 code = -errCode;
    const static CHAR* errDesp[] =
    {
                   "Succeed",
                   "IO Exception",
                   "Out of Memory",
                   "Permission Error",
                   "File Not Exist",
                   "File Exist",
                   "Invalid Argument",
                   "Invalid size",
                   "Interrupt",
                   "hit end of file",
                   "system error",
                   "has no space",
                   "EDU status is not valid",
                   "Timeout error",
                   "Database is quiesced",
                   "Network error",
                   "Network is closed from remote",
                   "Database is in shutdown status",
                   "Application is forced",
                   "Given path is not valid",
                   "Unexpected file type specified",
                   "There's no space for DMS",
                   "collection already exist",
                   "collection does not exist",
                   "user record is too big",
                   "record does not exist",
                   "remote overflow record exist",
                   "invalid record",
                   "storage unit need reorg",
                   "end of collection",
                   "context is already opened",
                   "context is closed",
                   "option is not supported yet",
                   "collection space already exist",
                   "collection space not exist",
                   "storage unit file is invalid",
                   "context not exist",
                   "more than one field has array",
                   "duplicate key exist",
                   "key is too large",
                   "index extent has no space",
                   "index key not exist",
                   "hit max number of index",
                   "failed to initialize index",
                   "collection is dropped",
                   "two records get same key and rid",
                   "duplicate index name",
                   "index name doesn't exist",
                   "index flag is unexpected",
                   "hit end of index",
                   "hit max of dedup buffer",
                   "invalid predicates",
                   "index is no longer exist",
                   "index hint is not valid",
                   "no more temp tables avaliable",
                   "exceed max number of SU",
                   "$id index can't be dropped",
                   "log was not found in log buf",
                   "log was not found in log file",
                   "replication group not exist",
                   "replication group exist",
                   "invalid request id is received",
                   "session ID does not exist",
                   "system edu can't be forced",
                   "database is not connected",
                   "unexpected result received",
                   "corrupted record",
                   "backup has already started",
                   "backup not completed",
                   "backup in progress mode",
                   "backup file is damaged",
                   "there's no primary found",
                   "the requested node not exist",
                   "engine help argument is specified",
                   "connection state is not valid",
                   "invalid handle",
                   "client object is freed",
                   "transfer has already listened",
                   "can not listen specified addr",
                   "cannot connect to specified addr",
                   "connection does not exist",
                   "failed to send",
                   "timer id not found",
                   "route info not found",
                   "broken msg",
                   "invalid net handle",
                   "reorg file is not valid",
                   "reorg file is in read only mode",
                   "collection status is not valid",
                   "collection is not in reorg state",
                   "replication group is not activated",
                   "the member is not in this group",
                   "collection flag not compatible",
                   "stroage unit version not compatible",
                   "local group version is expired",
                   "page size is not valid",
                   "remote group version is expired",
                   "failed to create a poll",
                   "log record is corrupted",
                   "given lsn greater than latest",
                   "received unknown mesage",
                   "updated information is same as old one",
                   "unknow message",
                   "empty heap",
                   "not primary",
                   "data node not enough",
                   "data node have no catalog info",
                   "data node catlog version old",
                   "coord node catalog version old",
                   "exceds the max group size",
                   "failed to sync log",
                   "failed to replay log",
                   "error http struct",
                   "failed to negotiate",
                   "failed to change dps metadata",
                   "SME is corrupted",
                   "application is interrupted",
                   "application is disconnected",
                   "character encoding errors",
                   "get failed msg from the node",
                   "buffer array is full",
                   "sub context is conflict",
                   "coord received EOC message",
                   "DPS file size are not the same",
                   "dps file not recognise",
                   "no resource",
                   "invalid lsn",
                   "data to pipe is too big",
                   "catalog auth failed",
                   "node is full sync",
                   "catnode failed assign data-node",
                   "php driver internal error",
                   "failed to send the message",
                   "there is no node-group register in catalogue-node",
                   "remote-node disconnected",
                   "couldn't find the match catalogue-info",
                   "update catalog failed",
                   "received invalid request which opcode is unknowned",
                   "coord couldn't find the group-info in local",
                   "dms extent is corrupted",
                   "remote cluster manage failed",
                   "remote engines have been stopped partially",
                   "sdb service is starting",
                   "sdb service has already been started",
                   "sdb service is restarting",
                   "sdb node is already existed",
                   "sdb node is not existed",
                   "unable to lock",
                   "dms state is not compatible with current command",
                   "rebuild has already started",
                   "rebuild in progress mode",
                   "there is no data in the coord-node's cache ",
                   "errors occur during the process of evalution",
                   "group already exist",
                   "group does not exist",
                   "node does not exist",
                   "failed to start the node",
                   "node'configure conflicts",
                   "group is empty",
                   "The operation is for coord node only",
                   "failed to operate on node only",
                   "The mutex job already exist",
                   "The specified job does not exist",
                   "The catalog information is corrupted",
                   "$shard index can't be dropped",
                   "The command can't be run in the node",
                   "The command can't be run in the serice plane",
                   "The group info not exist",
                   "Group name is conflict",
                   "The collection is not sharded",
                   "The record does not contains valid sharding key",
                   "A task that already exists does not compatible with the new task",
                   "The collection does not exists on the specified group",
                   "The specified task does not exist",
                   "The record contains more than one sharding key",
                   "The mutex task already exist",
                   "The split key is not valid or not in the source group",
                   "The unique index must include all fields in sharding key",
                   "Sharding key cannot be updated",
                   "authority is forbidden",
                   "There is no catalog address specified by user",
                   "current record has been deleted",
                   "search condition cannot match any records",
                   "index page is reorged and the pos got different lchild",
                   "There are duplicate field name exists in the record",
                   "Too many records to be inserted at once",
                   "Sort-Merge Join only supports equal predicates",
                   "Trace is already started",
                   "Trace buffer does not exist",
                   "Trace file is not valid",
                   "transaction-lock is incompatible",
                   "system is doing rollback",
                   "Bad record when doing sdb import ",
                   "repeat var name was found",
                   "column field is ambiguous",
                   "have an error in sql syntax",
                   "invalid transactional operation",
                   "append to lock-wait-queue",
                   "record is deleting",
                   "index is dropped or invalid",
                   "repeat to create catalog-group",
                   "parse json error",
                   "parse CSV error",
                   "log file is out of size",
                   "can not remove the only node in the group",
                   "need to manually complete the cleanup",
                   "can not remove node or group of catalog",
                   "group is not exist",
                   "can not remove the group with data in it",
                   "end of queue",
                   "collection has not sharding index, can not split by percent",
                   "the param field not exist",
                   "too many trace break points are specified",
                   "prefetchers are all busy",
                   "domain not exist",
                   "domain already exist",
                   "group is not in domain",
                   "sharding type is not hash",
                   "split percent is lower",
                   "task already finished, can not be caceled",
                   "collection is loading",
                   "load is error, and rollback",
                   "routeID is different from the local",
                   "service already exists",
                   "not find field",
                   "csv field line end",
                   "unknow file type",
                   "not all nodes are successful to export configuration",
                   "this node is not primary and has no data",
                   "secret value not same with data unit",
                   "engine version argument is specified",
                   "sdb help argument is specified",
                   "sdb version argument is specified",
                   "store procedure is not exist",
                   "illegal remove sub-collection",
                   "duplicate link sub-collection",
                   "invalid main-collection",
                   "new boundary is conflict with the existing boundary",
                   "new boundary is invalid",
                   "hit the high water mark",
                   "backup already exist",
                   "backup not exist",
                   "invalid sub-collection",
                   "task has canceled",
                   "the sharding-type of main-collection must be range",
                   "there is no valid sharding-key field",
                   "the operation not support on main-collection",
                   "redefine index",
                   "Deleting the CS",
                   "Reached the maximum number of nodes",
                   "the node is business-failures",
                   "the node info is expired",
                   "wait secondary nodes sync the operation failed",
                   "transaction is disabled",
                   "datasource had run out",
                   "too many open file description",
                   "Domain is not empty",
                   "Rest recv size greater than max size",
                   "Wrong data for building bson"
    };
    if ( code < 0 || (UINT32)code >= (sizeof ( errDesp ) / sizeof ( CHAR* )) )
        return "unknown error";
    return errDesp[code];
}
