#begin
log4j.rootLogger=DEBUG,myConsole,myLogFile
#console appender
log4j.appender.myConsole=org.apache.log4j.ConsoleAppender
log4j.appender.myConsole.layout=org.apache.log4j.PatternLayout
log4j.appender.myConsole.layout.ConversionPattern=[%d]-%m%n
log4j.appender.myConsole.threshold=info
#rolling file appender
log4j.appender.myLogFile=org.apache.log4j.FileAppender
log4j.appender.myLogFile.File=mylog.log
log4j.appender.myLogFile.Append=false
log4j.appender.myLogFile.layout=org.apache.log4j.PatternLayout
log4j.appender.myLogFile.layout.ConversionPattern=%m%n
log4j.appender.myLogFile.threshold=info
#end