EnsureSConsVersion( 1, 1, 0 )
import platform
import os
import re
from os.path import join, dirname, abspath

Import("env")
Import("dllBuildEnv")
Import("staticBuildEnv")
Import("client_lib_dir")

gtestFiles = [
   "../../../../../SequoiaDB/engine/gtest/src/gtest-all.cc"
]

testMainFile = [
   "./common/testMain.cpp"
]

clientStaticLib = [
   client_lib_dir + "/libstaticsdbc.a"
]

testCommonFiles = [
   "./common/testcommon.cpp",
   "./common/impWorker.cpp",
   "./common/arguments.cpp",
   "./common/testBase.cpp"
]

clientStaticLibFile = join( client_lib_dir, 'libstaticsdbc.a' )

testFiles = [
   [ "./concurrent/concurrentCl.cpp" ],
   [ "./concurrent/concurrentCs.cpp" ],
   [ "./concurrent/concurrentCursor.cpp" ],
   [ "./concurrent/concurrentDomain.cpp" ],  # sync
   [ "./concurrent/concurrentLob.cpp" ], 
   [ "./concurrent/concurrentNode.cpp" ], # sync
   [ "./concurrent/concurrentRg.cpp" ], # sync
   [ "./misc/JSCompatible.cpp" ],
   [ "./misc/analyze.cpp" ],
   [ "./misc/attachAndDetachNode.cpp" ], # sync
   [ "./misc/backup.cpp" ],
   [ "./misc/bson_array.cpp" ],
   [ "./misc/bson_oid.cpp" ],
   [ "./misc/code.cpp" ],
   [ "./misc/date.cpp" ],
   [ "./misc/decimal.cpp" ],
   [ "./misc/dropCsAndWriteLob.cpp" ],
   [ "./misc/forceSession.cpp" ],
   [ "./misc/handle.cpp" ],
   [ "./misc/idIndex.cpp" ],
   [ "./misc/index.cpp" ],
   [ "./misc/numberLong.cpp" ],
   [ "./misc/prepareMore.cpp" ],
   [ "./misc/procedure.cpp" ],
   [ "./misc/restAbnormal.cpp" ],
  #[ "./misc/socketMutex.cpp" ],
   [ "./misc/turnonCache.cpp" ],
   [ "./misc/sync.cpp" ],
   [ "./load/loadUnloadCS.cpp" ],
   [ "./load/reloadConf.cpp" ],
   [ "./load/rename.cpp" ],
   [ "./load/setPDLevel.cpp" ],
   [ "./ssl/sslFalse.cpp" ],
   [ "./ssl/sslTrue.cpp" ],  # conf
   [ "./lob/lobAbnormal.cpp" ],
   [ "./lob/lobNormal.cpp" ],
   [ "./tdd/bson_test.cpp" ],
   [ "./tdd/cbson.cpp" ],
   [ "./tdd/collection.cpp" ],
   [ "./tdd/collectionspace.cpp" ],
   [ "./tdd/concurrent_insert.cpp" ],
   [ "./tdd/cursor.cpp" ],
   [ "./tdd/debug.cpp" ],
   [ "./tdd/domain.cpp" ],
   [ "./tdd/mutex.cpp" ],
   [ "./tdd/newapi.cpp" ],
   [ "./tdd/rg.cpp" ],
   [ "./tdd/sdb.cpp" ],
   [ "./tdd/selector_query.cpp" ],
   [ "./tdd/shard.cpp" ],
   [ "./tdd/snapshot.cpp" ],
   [ "./tdd/lobTest.cpp" ],
   [ "./crud/updateShardingKey.cpp" ],
   [ "./crud/queryAndUpdateShardingKey.cpp" ],
   [ "./crud/upsertShardingKey.cpp"],
   [ "./crud/queryMeta.cpp" ]
]

def getFileName( filePath ):
   strArr = re.split( r'[/.]', filePath )
   # last element is suffix,
   # second last element is the name
   return strArr[-2]

def getObjectName( filePath ):
   return getFileName( filePath ) + ".o"

# add common to path
dllBuildEnv.Append( CPPPATH=[ "./common/" ] )
staticBuildEnv.Append( CPPPATH=[ "./common/" ] )

# compile common lib
gtestall = env.StaticLibrary('gtest', gtestFiles)

# complit main object file
testMainObj = dllBuildEnv.Object( [testMainFile] )

# compile common object file
commObj = []
for file in testCommonFiles:
   commonFileName = getFileName( file )
   commonFile = dllBuildEnv.Object( commonFileName, [file] )
   commObj.append( commonFile )

# compile test object file
objectFiles = []
for index in range( len(testFiles) ):
   objectFileArr = []
   for file in testFiles[index]:
      objectFileName = getObjectName( file )
      objectFile = dllBuildEnv.Object( objectFileName, [file] )
      objectFileArr.append( objectFile )
   objectFiles.append( objectFileArr )

# dll compile
dllPrograms = []
for index in range( len(testFiles) ):
   testFileName = getFileName( testFiles[index][0] )
   dllProgram = dllBuildEnv.Program( testFileName, [objectFiles[index], testMainObj, commObj] )
   dllPrograms.append( dllProgram )

# static compile
staticPrograms = []
for index in range( len(testFiles) ):
   testFileName = getFileName( testFiles[index][0] ) + ".static"
   staticProgram = staticBuildEnv.Program( testFileName, [objectFiles[index], testMainObj, commObj])
   staticPrograms.append( staticProgram )

# dll compile
env.Install( '#/build_test', dllPrograms )

# static compile
env.Install( '#/build_test', staticPrograms )
