# sdbcm default listening port
defaultPort=50010

# restart count, always restart if set "-1", never restart if set "0"
RestartCount=5
# restart time interval ( minute ), ignore this if resInterval <= 0
RestartInterval=0
AutoStart=true