instanceName,port,databaseDir,coordAddr
myinst,3306,[installPath]/database/myinst,-

# Note: coordAddr, '-' means the first coord in sdb.conf. You can configure it by format hostname1:coordPort1 or [hostname1:coordPort1,hostname2:coordPort2]