Import("env")
Import("root_dir")

clientFiles = [
      "pysequoiadb/pyclient.cpp",
      ]

clFiles = [
	  "pysequoiadb/pycollection.cpp",
	  ]

csFiles = [
	  "pysequoiadb/pycollectionspace.cpp",
	  ]

cursorFiles = [
	  "pysequoiadb/pycursor.cpp",
	  ]

replicagroupFiles = [
	   "pysequoiadb/pyreplicagroup.cpp",
	  ]

replicanodeFiles = [
	  "pysequoiadb/pyreplicanode.cpp",
	  ]

clientcppFiles = [
      root_dir + "/SequoiaDB/engine/client/clientcpp.cpp"
      ]

#for threadsafe build, we should add this into clientLibFiles
clientThreadSafe = [
      root_dir + "/SequoiaDB/engine/oss/ossLatch.cpp"
      ]

clientLibFiles = [
      root_dir + "/SequoiaDB/engine/oss/oss.cpp",
      root_dir + "/SequoiaDB/engine/oss/ossUtil.cpp",
	  root_dir + "/SequoiaDB/engine/oss/ossMem.cpp",
	  root_dir + "/SequoiaDB/engine/oss/ossVer.cpp",
	  root_dir + "/SequoiaDB/engine/oss/ossSocket.cpp",
	  root_dir + "/SequoiaDB/engine/oss/ossPrimitiveFileOp.cpp",
      root_dir + "/SequoiaDB/engine/pd/pd.cpp",
      root_dir + "/SequoiaDB/engine/pd/pdTrace.cpp",
	  root_dir + "/SequoiaDB/engine/pd/pdFunctionList.cpp",
	  root_dir + "/SequoiaDB/engine/client/bson/numbers.c",
	  root_dir + "/SequoiaDB/engine/client/bson/bson.c",
      root_dir + "/SequoiaDB/engine/client/bson/encoding.c",
	  root_dir + "/SequoiaDB/engine/client/base64c.c",
	  root_dir + "/SequoiaDB/engine/client/cJSON.c",
	  root_dir + "/SequoiaDB/engine/client/jstobs.c",
	  root_dir + "/SequoiaDB/engine/client/common.c",
	  root_dir + "/SequoiaDB/engine/util/fromjson.cpp",
      root_dir + "/SequoiaDB/engine/util/json2rawbson.c",
	  root_dir + "/SequoiaDB/engine/util/utilStr.cpp",
	  root_dir + "/SequoiaDB/engine/bson/bsonobj.cpp",
      root_dir + "/SequoiaDB/engine/bson/oid.cpp",
	  root_dir + "/SequoiaDB/engine/bson/md5.c",
      root_dir + "/SequoiaDB/engine/bson/base64.cpp",
      root_dir + "/SequoiaDB/engine/bson/nonce.cpp",
	  ]

env.Execute(Mkdir(root_dir + "/temp"))
env.Execute(Mkdir(root_dir + "/temp/bson"))
for file in clientcppFiles:
   env.Execute(Copy(root_dir + "/temp", file))
for file in clientLibFiles:
   env.Execute(Copy(root_dir + "/temp", file))
srcFile = [
	  root_dir + "/temp/clientcpp.cpp",
      root_dir + "/temp/oss.cpp",
      root_dir + "/temp/ossUtil.cpp",
	  root_dir + "/temp/ossMem.cpp",
	  root_dir + "/temp/ossVer.cpp",
	  root_dir + "/temp/ossSocket.cpp",
	  root_dir + "/temp/ossPrimitiveFileOp.cpp",
      root_dir + "/temp/pd.cpp",
      root_dir + "/temp/pdTrace.cpp",
	  root_dir + "/temp/pdFunctionList.cpp",
	  root_dir + "/temp/bson/numbers.c",
	  root_dir + "/temp/bson/bson.c",
      root_dir + "/temp/bson/encoding.c",
	  root_dir + "/temp/base64c.c",
	  root_dir + "/temp/cJSON.c",
	  root_dir + "/temp/jstobs.c",
	  root_dir + "/temp/common.c",
	  root_dir + "/temp/fromjson.cpp",
      root_dir + "/temp/json2rawbson.c",
	  root_dir + "/temp/utilStr.cpp",
	  root_dir + "/temp/bsonobj.cpp",
      root_dir + "/temp/oid.cpp",
	  root_dir + "/temp/md5.c",
      root_dir + "/temp/base64.cpp",
      root_dir + "/temp/nonce.cpp",
      ]

env.SharedLibrary('sdbclient',[ clientFiles, srcFile ])
env.SharedLibrary('sdbcl',[ clFiles, srcFile ])
env.SharedLibrary('sdbcs',[ csFiles, srcFile ])
env.SharedLibrary('sdbcursor',[ cursorFiles, srcFile ])
env.SharedLibrary('sdbreplicagroup',[ replicagroupFiles, srcFile ])
env.SharedLibrary('sdbreplicanode',[ replicanodeFiles, srcFile ])
