#sdbinspcect 的路径
proc=/opt/trunk/tools/sdbinspect

#sdb的路径
sdb=/opt/trunk/bin/sdb

#cs
cs_name=inspect_cs

#普通cl
cl_name=inspect_cl

#主表的cl
cl_main=maincl

#子表cl名字
cl1=cl1

#数据节点组
group_name=datagroup

#coord节点主机名
coordAddr=sdbserver3

#coord端口
coordPort=11810

#coord地址 
coord=$coordAddr:$coordPort

#数据节点主机名
dataAddr=sdbserver3

#数据节点端口号
dataPort=11820

#-w选项指定的名字
report_name=inspect

#生成的report名字
report_file=inspect.report

#生成的默认report名字
report_file_default=inspect.bin.report

