# (required)hostname of current cluster
# must be hostname rather than ip
host_name                      = "rhel64-test8,ubuntu1504"
# (required)root info
# when some hosts do not use default password of root account,
# we can add specified info like this: rhel64-test8_root_passwd = "xxx password xxx"
default_root_user              = "root"
default_root_passwd            = "sequoiadb"
# (required)ssh info
# when some hosts do not use default ssh port,
# we can add the specified info like this: rhel64-test8_ssh_port = xxx
default_ssh_port               = 22
# (required)database authentication info
db_auth_user                   = ""
db_auth_passwd                 = ""
# (required)configuration options for SequoiaDB nodes
db_config_option               = { svcscheduler:0 }
# (required)SequoiaDB install packet
db_install_packet              = "/opt/sequoiadb-1.12.6-linux_x86_64-enterprise-installer.run"



# (optional)cluster info
cluster_name                   = "myCluster"
cluster_description            = ""
sdb_admin_user_name            = "sdbadmin"
sdb_admin_password             = "sdbadmin"
sdb_default_install_path       = "/opt/sequoiadb"
# (optional)module info
module_name                    = "myModule"

