catalogConf        = {}
catalogDynaConf    = {}

coordConf          = {}
coordDynaConf      = {}

dataConf           = { transactionon:true }
dataDynaConf       = {}

standaloneConf     = { transactionon:true }
standaloneDynaConf = {}