import os
import re

Import("env")
Import("dllBuildEnv")
Import("staticBuildEnv")

gtestFiles = [ 
   "../../../../../SequoiaDB/engine/gtest/src/gtest-all.cc" 
]

testMainFile = [
   "./common/testMain.cpp"
]

testCommonFiles = [ 
   "./common/testcommon.cpp",
   "./common/impWorker.cpp",
   "./common/arguments.cpp",
   "./common/testBase.cpp"
]

testFiles = [ 
   [ "./datasource/DS_connTest9505.cpp" ],
   [ "./datasource/DS_invalidArgTest9524.cpp" ],
   [ "./datasource/DS_invalidConnTest9528.cpp" ],
   [ "./datasource/DS_invalidUsrTest9522.cpp" ],  # sync
   [ "./datasource/DS_threadTest9535.cpp", "./datasource/DS_thread.cpp" ],
   [ "./datasource/DS_timeTest9499.cpp" ],  # sync
   [ "./meta/domain12510_12658.cpp" ], # sync
   [ "./meta/domain12657.cpp" ], # sync
   [ "./meta/cs12511_12659.cpp" ],
   [ "./meta/cl12512_12747.cpp" ],
   [ "./meta/cl12660.cpp" ],
   [ "./index/index12514.cpp" ],
   [ "./index/idIndex12515.cpp" ],
   [ "./cursor/closeCursor12685_12686.cpp" ],
   [ "./cursor/closeAllCursors12687.cpp" ],
   [ "./dbOpr/auth12521.cpp" ],
   [ "./dbOpr/backup12304.cpp" ],
   [ "./disconnect/opCL12741.cpp" ],
   [ "./disconnect/opSdb12531.cpp" ],
   [ "./disconnect/opDomain12739.cpp" ],
   [ "./disconnect/opCS12740.cpp" ],
   [ "./disconnect/opCursor12742.cpp" ],
   [ "./disconnect/opRG12743.cpp" ],
   [ "./disconnect/opNode12744.cpp" ],
   [ "./disconnect/opLob12745.cpp" ],
   [ "./split/splitRange12682.cpp" ],
   [ "./split/splitHash12683.cpp" ],
   [ "./split/task12527.cpp" ],
   [ "./crud/bulkInsert12540_12666.cpp" ],
   [ "./crud/setSessionAttr12538.cpp" ],
   [ "./crud/upsert12541.cpp" ],
   [ "./crud/upsertShardingKey12637.cpp" ],
   [ "./crud/truncate12667.cpp" ],
   [ "./crud/queryOne12542.cpp" ],
   [ "./crud/queryAndRemove12544.cpp" ],
   [ "./crud/queryAndUpdate12543.cpp" ],
   [ "./crud/queryAndUpdateShardingKey12636.cpp" ],
   [ "./decimal/absAndGetSign8892.cpp" ],
   [ "./decimal/add8895.cpp" ],
   [ "./decimal/append8865.cpp" ],
   [ "./decimal/ceilAndFloor8902.cpp" ],
   [ "./decimal/compare8893.cpp" ],
   [ "./decimal/div8899.cpp" ],
   [ "./decimal/getPercision8891.cpp" ],
   [ "./decimal/insAndQry8887.cpp" ],
   [ "./decimal/max8881.cpp" ],
   [ "./decimal/min8879.cpp" ],
   [ "./decimal/mod8904.cpp" ],
   [ "./decimal/mul8898.cpp" ],
   [ "./decimal/sub8897.cpp" ],
   [ "./decimal/zero8877.cpp" ]
]

def getFileName( filePath ):
   strArr = re.split( r'[/.]', filePath )
   # last element is suffix, 
   # second last element is the name
   return strArr[-2]

def getObjectName( filePath ):
   return getFileName( filePath ) + ".o"
                      
# add common to path
dllBuildEnv.Append( CPPPATH=[ "./common/" ] )
staticBuildEnv.Append( CPPPATH=[ "./common/" ] )

# compile common lib
gtestall = env.StaticLibrary('gtest', gtestFiles)

# complit main object file
testMainObj = dllBuildEnv.Object( [testMainFile] )

# compile common object file
commObj = []
for file in testCommonFiles:
   commonFileName = getFileName( file )
   commonFile = dllBuildEnv.Object( commonFileName, [file] )
   commObj.append( commonFile ) 

# compile test object file
objectFiles = []
for index in range( len(testFiles) ):
   objectFileArr = []
   for file in testFiles[index]:
      objectFileName = getObjectName( file )
      objectFile = dllBuildEnv.Object( objectFileName, [file] )
      objectFileArr.append( objectFile )
   objectFiles.append( objectFileArr ) 

# dll compile
dllPrograms = []
for index in range( len(testFiles) ):
   testFileName = getFileName( testFiles[index][0] )
   dllProgram = dllBuildEnv.Program( testFileName, [objectFiles[index], testMainObj, commObj] )
   dllPrograms.append( dllProgram )

# static compile
staticPrograms = []
for index in range( len(testFiles) ):
   testFileName = getFileName( testFiles[index][0] ) + ".static"
   staticProgram = staticBuildEnv.Program( testFileName, [objectFiles[index], testMainObj, commObj])
   staticPrograms.append( staticProgram )

# dll install
env.Install( '#/build_test', dllPrograms )

# static install
env.Install( '#/build_test', staticPrograms )
