import os
import re

Import("env")
Import("dllBuildEnv")
Import("staticBuildEnv")

gtestFiles = [ 
   "../../../../../SequoiaDB/engine/gtest/src/gtest-all.cc" 
]

testMainFile = [
   "./common/testMain.cpp"
]

testCommonFiles = [ 
   "./common/testcommon.cpp",
   "./common/impWorker.cpp",
   "./common/arguments.cpp",
   "./common/testBase.cpp"
]

testFiles = [ 
   [ "./datasource/DS_connTest9505.cpp" ],
]

def getFileName( filePath ):
   strArr = re.split( r'[/.]', filePath )
   # last element is suffix, 
   # second last element is the name
   return strArr[-2]
                      
# add common to path
dllBuildEnv.Append( CPPPATH=[ "./common/" ] )
staticBuildEnv.Append( CPPPATH=[ "./common/" ] )

# compile common lib
gtestall = env.StaticLibrary('gtest', gtestFiles)

# dll compile
dllPrograms = []
for testFile in testFiles:
   testFileName = getFileName( testFile[0] )
   dllProgram = dllBuildEnv.Program( testFileName, [testFile, testMainFile, testCommonFiles] )
   dllPrograms.append( dllProgram )

# static compile
staticPrograms = []
for testFile in testFiles:
   testFileName = getFileName( testFile[0] ) + ".static"
   staticProgram = staticBuildEnv.Program( testFileName, [testFile, testMainFile, testCommonFiles])
   staticPrograms.append( staticProgram )

# dll install
env.Install( '#/build_test', dllPrograms )

# static install
env.Install( '#/build_test', staticPrograms )
