load=True
newOrderWeight=45
terminalWarehouseFixed=true
runMins=30
stockLevelWeight=4
testType=fdw
runTxnsPerTerminal=0
//conn=jdbc:postgresql://192.168.30.50:5432/benchmarksql,jdbc:postgresql://192.168.30.50:5430/benchmarksql,jdbc:postgresql://192.168.30.51:5432/benchmarksql,jdbc:postgresql://192.168.30.51:5430/benchmarksql
conn=jdbc:postgresql://192.168.30.50:5432/benchmarksql
osCollectorSSHAddr=root@192.168.30.50,root@192.168.30.51
warehouses=2000
osCollectorDevices=192.168.30.50:net_em1 blk_sdb blk_sdc blk_sdd blk_sde blk_sdf blk_sdg,192.168.30.51:net_em1 blk_sdb blk_sdc blk_sdd blk_sde blk_sdf blk_sdg
deliveryWeight=4
paymentWeight=43
osCollectorScript=./misc/os_collector_linux.py
osCollectorInterval=1
driver=org.postgresql.Driver
db=postgres
terminals=200
resultDirectory=tpc_result2
user=benchmarksql
password=changeme
osCollectorHardWare=./misc/collector_hardware.py
orderStatusWeight=4
limitTxnsPerMin=30000
sdburl=192.168.30.50:11810,192.168.30.50:11800,192.168.30.51:11800,192.168.30.51:11810
osCollectorSoftWare=./misc/collector_software.py
loadWorkers=50
