import os

Import("env")
Import("dllBuildEnv")
Import("staticBuildEnv")

gtestFiles = [
      "../../../../../SequoiaDB/engine/gtest/src/gtest-all.cc"
      ]

gtestMainFile = [
      "../../../../../SequoiaDB/engine/gtest/src/gtest_main.cc"
      ]

testCommonFiles = [
        "testcommon.cpp","DS_impWorker.cpp","DS_thread.cpp"
      ]

testFiles1 = [ "decimal.cpp" ]

testFiles2 = [ "numberLong.cpp" ]

testFiles3 = [ "trunOncache.cpp" ]

testFiles4 = [ "time.cpp" ] 

testFiles5 = [ "DS_InvalidArgTest.cpp" ]

testFiles6 = [ "DS_InvalidConnTest.cpp" ]

testFiles7 = [ "DS_ConnTest.cpp" ]

testFiles8 = [ "DS_ThreadTest.cpp" ]

testFiles9 = [ "DS_ChecktimeTest.cpp" ]

testFiles10 = [ "DS_ClTest.cpp" ]

# compile common lib
gtestall = env.StaticLibrary('gtest', gtestFiles)
gtestMainObj = env.Object('gtestMainObj', gtestMainFile)

# dll compile
decimal        = dllBuildEnv.Program("decimal",       [testFiles1, gtestMainObj, testCommonFiles])
numberLong     = dllBuildEnv.Program("numberLong",    [testFiles2, gtestMainObj, testCommonFiles])
trunOncache    = dllBuildEnv.Program("trunOncache",   [testFiles3, gtestMainObj, testCommonFiles])
time           = dllBuildEnv.Program("time",          [testFiles4, gtestMainObj, testCommonFiles])
DS_InvalidArgTest = dllBuildEnv.Program("DS_InvalidArgTest", [testFiles5, gtestMainObj])
DS_InvalidConnTest = dllBuildEnv.Program("DS_InvalidConnTest", [testFiles6, gtestMainObj])
DS_ConnTest = dllBuildEnv.Program("DS_ConnTest", [testFiles7, gtestMainObj])
DS_ThreadTest = dllBuildEnv.Program("DS_ThreadTest", [testFiles8, gtestMainObj,testCommonFiles])
DS_ChecktimeTest = dllBuildEnv.Program("DS_ChecktimeTest", [testFiles9, gtestMainObj])
DS_ClTest = dllBuildEnv.Program("DS_ClTest", [testFiles10, gtestMainObj])  

# static compile
# dll compile
decimal.static       = staticBuildEnv.Program("decimal.static",      [testFiles1, gtestMainObj, testCommonFiles])
numberLong.static    = staticBuildEnv.Program("numberLong.static",   [testFiles2, gtestMainObj, testCommonFiles])
trunOncache.static   = staticBuildEnv.Program("trunOncache.static",  [testFiles3, gtestMainObj, testCommonFiles])
time.static          = staticBuildEnv.Program("time.static",         [testFiles4, gtestMainObj, testCommonFiles])
DS_InvalidArgTest.static = staticBuildEnv.Program("DS_InvalidArgTest.static",[testFiles5, gtestMainObj])
DS_InvalidConnTest.static = staticBuildEnv.Program("DS_InvalidConnTest.static",[testFiles6, gtestMainObj])
DS_ConnTest.static = staticBuildEnv.Program("DS_ConnTest.static",[testFiles7, gtestMainObj])
DS_ThreadTest.static = staticBuildEnv.Program("DS_ThreadTest.static",[testFiles8, gtestMainObj,testCommonFiles])
DS_ChecktimeTest.static = staticBuildEnv.Program("DS_ChecktimeTest.static",[testFiles9, gtestMainObj])
DS_ClTest.static = staticBuildEnv.Program("DS_ClTest.static",[testFiles10, gtestMainObj])

# dll compile
env.Install( '#/build_test',[ decimal,numberLong,trunOncache,time,DS_InvalidArgTest,
							  DS_InvalidConnTest,DS_ConnTest,DS_ThreadTest,DS_ChecktimeTest,DS_ClTest ] )

# static compile
env.Install( '#/build_test',[ decimal.static,numberLong.static,trunOncache.static,
							  time.static,DS_InvalidArgTest.static,DS_InvalidConnTest.static,
							  DS_ConnTest.static,DS_ThreadTest.static,DS_ChecktimeTest.static,DS_ClTest.static ] )

