server.port=8002
server.tomcat.max-threads=200
server.tomcat.min-spare-threads=5


sdbs3.sequoiadb.url=sequoiadb://192.168.20.56:11810
sdbs3.sequoiadb.meta.csName=csmeta
sdbs3.sequoiadb.meta.clName=cl

sdbs3.sequoiadb.data.csName=csdata
sdbs3.sequoiadb.data.archiverate=year
