server.port=8002
server.tomcat.max-threads=200
server.tomcat.min-spare-threads=5

sdbs3.sequoiadb.url=sequoiadb://192.168.20.69:12900
sdbs3.sequoiadb.meta.csName=MetaCollectionSpace

sdbs3.sequoiadb.data.csName=DataCollectionSpace
sdbs3.sequoiadb.data.archiverate=year

sdbs3.bucket.limit=100
