server.port=8002
server.tomcat.max-threads=200
server.tomcat.min-spare-threads=5

sdbs3.sequoiadb.url=sequoiadb://192.168.20.69:12900,192.168.20.69:12910,192.168.20.69:12920
sdbs3.sequoiadb.meta.csName=MetaCollectionSpace
sdbs3.sequoiadb.data.csName=DataCollectionSpace
sdbs3.sequoiadb.data.csRate=year
sdbs3.sequoiadb.data.clRate=mounth

# bucket number limit
sdbs3.bucket.limit=100

# unit is minute
sdbs3.context.lifecycle=60
# context cron
sdbs3.context.cron=0 0/1 * * * *
