#WORKSPACE=/home/jenkins/workspace/test
#DBUILD_NUMBER=999

G1D3_HOST=ci-test-cent1,ci-test-cent2,ci-test-cent3
G3D3_HOST=ubuntu-200-037,ubuntu-200-038,ubuntu-200-039
STANDALONE_HOST=ubuntu-200-037
INSTALL_DIR=/opt/sequoiadb
CI_WORK_DIR=/tmp/ci
SVCNAME=11810
BACKLOG_DIR=/opt/backup
JENKINS_MASTER_IP=192.168.30.184






