
x86_NORMALTEST_G1D3_HOST       =ci-test-cent1,ci-test-cent2,ci-test-cent3
x86_NORMALTEST_G3D3_HOST       =ci-test-suse2,ci-test-suse3,ci-test-suse4
x86_NORMALTEST_STANDALONE_HOST =ci-test-suse1

x86_LARGEDATATEST_G3D3_HOST    =ci-test-rhel1,ci-test-rhel2,ci-test-rhel3

PPC_NORMALTEST_G3D_HOST        =ci-test-ppc-rhel2,ci-test-ppc-rhel1,ci-test-ppc-suse1

INSTALL_DIR=/opt/sequoiadb
CI_WORK_DIR=/tmp/ci
SVCNAME=11810

BACKLOG_DIR=/opt/ci/backup_log
JENKINS_HOST=jenkins-master






