#ifndef DPSDEF_HPP_
#define DPSDEF_HPP_

#if defined (_WINDOWS)
#define DPS_INVALID_LSN_OFFSET 0xFFFFFFFFFFFFFFFFLL
#elif defined (_LINUX)
#define DPS_INVALID_LSN_OFFSET 0xFFFFFFFFFFFFFFFFll
#endif
#define DPS_MERGE_BLOCK_MAX_DATA 10
#define DPS_INVALID_LSN_VERSION 0

#define DPS_DEFAULT_PAGE_SIZE  ( 64 * 1024 )
#define DPS_LOG_HEAD_LEN ( 64 * 1024 )

#define DPS_DMP_OPT_HEX            0x00000001
#define DPS_DMP_OPT_HEX_WITH_ASCII 0x00000002
#define DPS_DMP_OPT_FORMATTED      0x00000004
#define DPS_INVALID_TRANS_ID        0

#define DPS_INVALID_TAG 0
#define DPS_DUMMY_TAG 256
#define DPS_TAG UINT8

typedef UINT64 DPS_TRANS_ID;
typedef UINT64 DPS_LSN_OFFSET ;
typedef UINT32 DPS_LSN_VER ;
typedef UINT16 DPS_LSN_V_HALF ;

enum DPS_LOG_TYPE
{
   LOG_TYPE_DUMMY        = 0x00,
   LOG_TYPE_DATA_INSERT  = 0x01,
   LOG_TYPE_DATA_UPDATE  = 0x02,
   LOG_TYPE_DATA_DELETE  = 0x03,
   LOG_TYPE_CS_CRT       = 0x04,
   LOG_TYPE_CS_DELETE    = 0x05,
   LOG_TYPE_CL_CRT       = 0x06,
   LOG_TYPE_CL_DELETE    = 0x07,
   LOG_TYPE_IX_CRT       = 0x08,
   LOG_TYPE_IX_DELETE    = 0x09,
   LOG_TYPE_CL_RENAME    = 0x0A,
   LOG_TYPE_CL_TRUNC     = 0x0B,
   LOG_TYPE_TS_COMMIT    = 0x0C,
   LOG_TYPE_TS_ROLLBACK  = 0x0D,
   LOG_TYPE_INVALIDATE_CATA   = 0x0E
};

#endif
