/*******************************************************************************


   Copyright (C) 2011-2014 SequoiaDB Ltd.

   This program is free software: you can redistribute it and/or modify
   it under the term of the GNU Affero General Public License, version 3,
   as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warrenty of
   MARCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program. If not, see <http://www.gnu.org/license/>.

   Source File Name = optAccessPlan.hpp

   Descriptive Name = Optimizer Access Plan Header

   When/how to use: this program may be used on binary and text-formatted
   versions of Optimizer component. This file contains structure for access
   plan, which is indicating how to run a given query.

   Dependencies: N/A

   Restrictions: N/A

   Change Activity:
   defect Date        Who Description
   ====== =========== === ==============================================
          09/14/2012  TW  Initial Draft

   Last Changed =

*******************************************************************************/
#ifndef OPTACCESSPLAN_HPP__
#define OPTACCESSPLAN_HPP__

#include "core.hpp"
#include "oss.hpp"
#include "rtnPredicate.hpp"
#include "mthMatchTree.hpp"
#include "ossAtomic.hpp"
#include "../bson/oid.h"
#include "../bson/bson.h"
#include "ossUtil.hpp"
#include "optPlanPath.hpp"
#include "utilHashTable.hpp"
#include "optAccessPlanKey.hpp"

using namespace bson ;

namespace engine
{
   class _optAccessPlanManager ;

   #define OPT_INVALID_ACT_ID ( -1 )

   // note _optAccessPlan object should NEVER been deleted by caller other than
   // _rtnAccessPlanList, user should call getPlan and releasePlan to make sure
   // all plans are properly tracked
   class _optAccessPlan : public _utilHashTableItem
   {
   private:
      optAccessPlanKey _key ;
      _mthMatchTree _matcher ;      // matcher that should be used by the plan
      rtnPredicateList *_predList ; // predicate list that generated from
                                    // matcher and index

      BOOLEAN _hintFailed ;

      BOOLEAN _isInitialized ;

      BOOLEAN _isAutoPlan ;         // auto plan, TRUE when the plan is not
                                    // generated by hint or hint is not valid
      BOOLEAN _autoHint ;

      optPlanAllocator _planAllocator ;
      optScanPath _scanPath ;

      ossAtomicSigned32 _activityID ;
      ossAtomic32 _refCount ;

      UINT32 _useCount ;

   private:
      INT32 _checkOrderBy() ;

      INT32 _estimateHintPlans ( dmsStorageUnit *su,
                                 dmsMBContext *mbContext,
                                 dmsStatCache *statCache ) ;

      INT32 _estimatePlans ( dmsStorageUnit *su,
                             dmsMBContext *mbContext,
                             dmsStatCache *statCache ) ;

      INT32 _estimateIxScanPlan ( dmsStorageUnit *su,
                                  dmsMBContext *mbContext,
                                  optCollectionStat &collectionStat,
                                  const CHAR *pIndexName,
                                  OPT_PLAN_PATH_PRIORITY priority,
                                  UINT64 sortBufferSize,
                                  INT32 estCacheSize,
                                  optScanPath &ixScanPath ) ;

      INT32 _estimateIxScanPlan ( dmsStorageUnit *su,
                                  dmsMBContext *mbContext,
                                  optCollectionStat &collectionStat,
                                  const OID &indexOID,
                                  OPT_PLAN_PATH_PRIORITY priority,
                                  UINT64 sortBufferSize,
                                  INT32 estCacheSize,
                                  optScanPath &ixScanPath ) ;

      INT32 _estimateIxScanPlan ( dmsStorageUnit *su,
                                  optCollectionStat &collectionStat,
                                  dmsExtentID indexCBExtent,
                                  OPT_PLAN_PATH_PRIORITY priority,
                                  UINT64 sortBufferSize,
                                  INT32 estCacheSize,
                                  optScanPath &ixScanPath ) ;

      INT32 _estimateTbScanPlan ( optCollectionStat &collectionStat,
                                  UINT64 sortBufferSize,
                                  INT32 estCacheSize,
                                  optScanPath &tbScanPath ) ;

      INT32 _usePath ( dmsStorageUnit *su, optScanPath &path ) ;

      OSS_INLINE BOOLEAN _isCached () const
      {
         return ( NULL != _pList ) ;
      }

      INT32 _prepareOptimize ( dmsStorageUnit *su,
                               dmsMBContext *mbContext ) ;

   public :
      _optAccessPlan ( const optAccessPlanKey &planKey, BOOLEAN needGetOwned ) ;

      virtual ~_optAccessPlan ()
      {
         UINT32 refCount = getRefCount() ;
         if ( refCount != 0 )
         {
            PD_LOG ( PDWARNING, "Plan[%s] is deleted when use count is "
                     "not 0: %d", toString().c_str(), refCount ) ;
         }
         if ( _predList )
         {
            SDB_OSS_DEL _predList ;
         }
      }

      optScanType getScanType()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _scanPath.getScanType() ;
      }

      BOOLEAN isHintFailed() const { return _hintFailed ; }

      INT32 optimize ( dmsStorageUnit *su, dmsMBContext *mbContext ) ;

      // matcher and predlist must be used after optimize.
      _mthMatchTree &getMatcher()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _matcher ;
      }

      rtnPredicateList *getPredList ()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _predList ;
      }

      INT32 getDirection ()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _scanPath.getDirection() ;
      }

      dmsExtentID getIndexCBExtent () const
      {
         return _scanPath.getIndexExtID() ;
      }

      const CHAR *getIndexName() const
      {
         return _scanPath.getIndexName() ;
      }

      dmsExtentID getIndexLID () const
      {
         return _scanPath.getIndexLID() ;
      }

      OSS_INLINE dmsStorageUnitID getSUID () const
      {
         return _key._suID ;
      }

      OSS_INLINE UINT32 getSULID () const
      {
         return _key._suLID ;
      }

      OSS_INLINE const CHAR *getCLFullName () const
      {
         return _key._fullName ;
      }

      OSS_INLINE UINT16 getCLMBID () const
      {
         return _key._mbID ;
      }

      OSS_INLINE UINT32 getCLLID () const
      {
         return _key._clLID ;
      }

      void release () ;

      BOOLEAN sortRequired()
      {
         return _scanPath.isSortRequired() ;
      }

      BOOLEAN isAutoGen ()
      {
         return _isAutoPlan ;
      }

      std::string toString() const ;

      OSS_INLINE void toBSON( BSONObjBuilder &builder ) const
      {
         _scanPath.toBSON( builder ) ;
      }

      OSS_INLINE virtual const optAccessPlanKey &getKey () const
      {
         return _key ;
      }

      OSS_INLINE BOOLEAN isEqual ( const optAccessPlanKey &key ) const
      {
         return _key.isEqual( key ) ;
      }

      OSS_INLINE virtual BOOLEAN isEqual ( const _optAccessPlan &item ) const
      {
         return _key.isEqual( item._key ) ;
      }

      OSS_INLINE virtual UINT32 getKeyCode () const
      {
         return _key.getKeyCode () ;
      }

      OSS_INLINE void setActivityID ( INT32 activityID )
      {
         // No need to check
         _activityID.init( activityID ) ;
      }

      OSS_INLINE BOOLEAN resetActivityID ( INT32 oldID, INT32 newID )
      {
         return _activityID.compareAndSwap( oldID, newID ) ;
      }

      OSS_INLINE INT32 resetActivityID ()
      {
         // Already reset by others
         return _activityID.swap( OPT_INVALID_ACT_ID ) ;
      }

      OSS_INLINE INT32 getActivityID () const
      {
         return _activityID.peek() ;
      }

      OSS_INLINE UINT32 getUseCount () const
      {
         return _useCount ;
      }

      OSS_INLINE UINT32 getRefCount () const
      {
         return _refCount.peek() ;
      }

      OSS_INLINE UINT32 incRefCount ()
      {
         _useCount ++ ;
         return _refCount.inc() ;
      }

      OSS_INLINE UINT32 decRefCount ()
      {
         return _refCount.dec() ;
      }

   } ;

   typedef class _optAccessPlan optAccessPlan ;

}

#endif //OPTACCESSPLAN_HPP__

