/*******************************************************************************


   Copyright (C) 2011-2014 SequoiaDB Ltd.

   This program is free software: you can redistribute it and/or modify
   it under the term of the GNU Affero General Public License, version 3,
   as published by the Free Software Foundation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warrenty of
   MARCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
   GNU Affero General Public License for more details.

   You should have received a copy of the GNU Affero General Public License
   along with this program. If not, see <http://www.gnu.org/license/>.

   Source File Name = optAccessPlan.hpp

   Descriptive Name = Optimizer Access Plan Header

   When/how to use: this program may be used on binary and text-formatted
   versions of Optimizer component. This file contains structure for access
   plan, which is indicating how to run a given query.

   Dependencies: N/A

   Restrictions: N/A

   Change Activity:
   defect Date        Who Description
   ====== =========== === ==============================================
          09/14/2012  TW  Initial Draft

   Last Changed =

*******************************************************************************/
#ifndef OPTACCESSPLAN_HPP__
#define OPTACCESSPLAN_HPP__

#include "core.hpp"
#include "oss.hpp"
#include "rtnPredicate.hpp"
#include "dms.hpp"
#include "mthMatchTree.hpp"
#include "ixm.hpp"
#include "ossAtomic.hpp"
#include "../bson/oid.h"
#include "../bson/bson.h"
#include "ossUtil.hpp"
#include "optPlanPath.hpp"

using namespace bson ;

namespace engine
{
   class _dmsMBContext ;
   class _dmsStorageUnit ;
   class _rtnAccessPlanManager ;

   // note _optAccessPlan object should NEVER been deleted by caller other than
   // _rtnAccessPlanList, user should call getPlan and releasePlan to make sure
   // all plans are properly tracked
   class _optAccessPlan : public SDBObject
   {
   private:

      _mthMatchTree _matcher ;      // matcher that should be used by the plan
      rtnPredicateList *_predList ; // predicate list that generated from
                                    // matcher and index
      _dmsStorageUnit *_su ;        // pointer for the storage unit
      _rtnAccessPlanManager *_apm ; // parent access plan manager

      CHAR _collectionName[ DMS_COLLECTION_NAME_SZ+1 ] ;
      CHAR _collectionFullName[ DMS_COLLECTION_FULL_NAME_SZ + 1 ] ;
      CHAR _idxName[IXM_INDEX_NAME_SIZE + 1] ;

      BSONObj _selector ;           // selector
      BSONObj _orderBy ;            // order by called by the user
      BSONObj _queryMatchter ;      // query condition called by the user
      BSONObj _hint ;               // hint called by the user
      BOOLEAN _hintFailed ;

      SINT32  _queryFlags ;
      SINT64  _numToSkip ;
      SINT64  _numToReturn ;

      BOOLEAN     _isInitialized ;
      BOOLEAN     _isValid ;

      BOOLEAN _isAutoPlan ;         // auto plan, TRUE when the plan is not
                                    // generated by hint or hint is not valid
      UINT32 _hashValue ;
      ossAtomicSigned32 _useCount ;
      BOOLEAN _autoHint ;

      optPlanAllocator _planAllocator ;
      optScanPath _scanPath ;

   private:
      INT32 _checkOrderBy() ;

      INT32 _estimateHintPlans ( _dmsMBContext *mbContext ) ;

      INT32 _estimatePlans ( _dmsMBContext *mbContext ) ;

      INT32 _estimateIxScanPlan ( rtnCollectionStat &collectionStat,
                                  dmsExtentID indexCBExtent,
                                  OPT_PLAN_PATH_PRIORITY priority,
                                  UINT64 sortBufferSize,
                                  INT32 estCacheSize,
                                  optScanPath &path ) ;

      INT32 _estimateTbScanPlan ( const rtnCollectionStat &collectionStat,
                                  UINT64 sortBufferSize,
                                  INT32 estCacheSize,
                                  optScanPath &path ) ;

      INT32 _usePath ( optScanPath &path ) ;

   public :
      _optAccessPlan ( _dmsStorageUnit *su, const CHAR *collectionName,
                       const BSONObj &selector, const BSONObj &matcher,
                       const BSONObj &orderBy, const BSONObj &hint,
                       SINT32 flags, SINT64 numToSkip, SINT64 numToReturn ) ;

      ~_optAccessPlan()
      {
         if ( _useCount.peek() != 0 )
         {
            PD_LOG ( PDWARNING, "Plan[%s] is deleted when use count is "
                     "not 0: %d", toString().c_str(),
                     _useCount.peek() ) ;
         }
         if ( _predList )
         {
            SDB_OSS_DEL _predList ;
         }
      }

      optScanType getScanType()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _scanPath.getScanType() ;
      }

      void incCount( INT32 inc = 1 )
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         _useCount.add ( inc ) ;
      }

      void decCount( INT32 dec = 1 )
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         _useCount.sub ( dec ) ;
      }

      INT32 getCount()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _useCount.peek() ;
      }

      BOOLEAN isHintFailed() const { return _hintFailed ; }

      INT32 optimize() ;

      // matcher and predlist must be used after optimize.
      _mthMatchTree &getMatcher()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _matcher ;
      }

      rtnPredicateList *getPredList ()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _predList ;
      }

      INT32 getDirection ()
      {
         SDB_ASSERT ( _isInitialized,
                      "optAccessPlan must be optimized before start using" ) ;
         return _scanPath.getDirection() ;
      }

      dmsExtentID getIndexCBExtent () const
      {
         return _scanPath.getIndexExtID() ;
      }

      const CHAR *getIndexName() const
      {
         return _scanPath.getIndexName() ;
      }

      dmsExtentID getIndexLID () const
      {
         return _scanPath.getIndexLID() ;
      }

      BOOLEAN Reusable ( const BSONObj &matcher, const BSONObj &orderBy,
                         const BSONObj &hint, SINT32 flags ) const ;

      // get hash result for the plan
      UINT32 hash ()
      {
         return _hashValue ;
      }

      static UINT32 hash ( const BSONObj &matcher, const BSONObj &orderBy,
                           const BSONObj &hint ) ;

      const CHAR *getName()
      {
         return _collectionName ;
      }

      void setAPM ( _rtnAccessPlanManager *apm )
      {
         _apm = apm ;
      }

      _rtnAccessPlanManager *getAPM()
      {
         return _apm ;
      }

      void release() ;

      BOOLEAN sortRequired()
      {
         return _scanPath.isSortRequired() ;
      }

      void setValid ( BOOLEAN valid )
      {
         _isValid = valid ;
      }

      BOOLEAN getValid ()
      {
         return _isValid ;
      }

      BOOLEAN isAutoGen ()
      {
         return _isAutoPlan ;
      }

      std::string toString() const ;

      OSS_INLINE void toBSON( BSONObjBuilder &builder ) const
      {
         _scanPath.toBSON( builder ) ;
      }

   } ;
   typedef class _optAccessPlan optAccessPlan ;

}

#endif //OPTACCESSPLAN_HPP__

