#properties文件在conf目录下

#md文件路径
mdPath = conf/mdPath.xml
#整合md输出路径
outputMD = docs/SequoiaDB_Doc.md
#pdf输出路径
outputPDF = docs/SequoiaDB_Doc.pdf
#word docx 输出路径
outputDocx = docs/SequoiaDB_Doc.docx
#doxygen配置文件路径
doxygenPath = conf/doxygenPath.xml