EnsureSConsVersion( 1, 1, 0 )
import platform
import os
import re
from os.path import join, dirname, abspath

Import("env")
Import("dllBuildEnv")
Import("staticBuildEnv")
Import("client_lib_dir")

gtestFiles = [
      "../../../../../SequoiaDB/engine/gtest/src/gtest-all.cc"
      ]

gtestMainFile = [
      "../../../../../SequoiaDB/engine/gtest/src/gtest_main.cc"
      ]

clientStaticLib = [
       client_lib_dir + "/libstaticsdbc.a"
       ]

testCommonFiles = [
      "./common/testcommon.c","./common/impWorker.cpp"
      ]

clientStaticLibFile = join( client_lib_dir, 'libstaticsdbc.a' )

testFiles1 = [ "./misc/decimal.cpp" ]

testFiles2 = [ "./misc/numberLong.cpp" ]
      
testFiles3 = [ "./misc/trunOncache.cpp" ]

testFiles4 = [ "./misc/restAbnormal.cpp" ]

testFiles5 = [ "./misc/procedure.cpp" ]

testFiles6 = [ "./misc/socketMutex.cpp" ] 

testFiles7 = [ "./misc/index.cpp" ]

testFiles8 = [ "./misc/dropCsAndWriteLob.cpp" ]

testFiles9 = [ "./concurrent/concurrentCs.cpp" ]

testFiles10 = [ "./concurrent/concurrentCl.cpp" ]

testFiles11 = [ "./concurrent/concurrentLob.cpp" ]

testFiles12 = [ "./concurrent/concurrentCursor.cpp" ]

testFiles13 = [ "./lob/lobNormal.cpp" ]

testFiles14 = [ "./lob/lobAbnormal.cpp" ] 


# compile common lib
gtestall = env.StaticLibrary('gtest', gtestFiles)
gtestMainObj = env.Object('gtestMainObj', gtestMainFile)
testCommon = env.StaticLibrary("testCommon", [testCommonFiles])

# dll compile

# test = dllBuildEnv.Program("test",       [testFiles, testCommon, gtestMainObj])

decimal        = dllBuildEnv.Program("decimal",       [testFiles1, testCommon, gtestMainObj])
numberLong     = dllBuildEnv.Program("numberLong",    [testFiles2, testCommon, gtestMainObj])
turnOncache    = dllBuildEnv.Program("turnOncache",   [testFiles3, testCommon, gtestMainObj])
restAbnormal   = dllBuildEnv.Program("restAbnormal",  [testFiles4, testCommon, gtestMainObj])
procedure      = dllBuildEnv.Program("procedure",  [testFiles5, testCommon, gtestMainObj])
socketMutex    = dllBuildEnv.Program("socketMutex",  [testFiles6, testCommon, gtestMainObj])
index          = dllBuildEnv.Program("index",  [testFiles7, testCommon, gtestMainObj])
dropCsAndWriteLob = dllBuildEnv.Program("dropCsAndWriteLob",  [testFiles8, testCommon, gtestMainObj])
concurrentCs   = dllBuildEnv.Program("concurrentCs",  [testFiles9, testCommon, gtestMainObj])
concurrentCl   = dllBuildEnv.Program("concurrentCl",  [testFiles10, testCommon, gtestMainObj])
concurrentLob     = dllBuildEnv.Program("concurrentLob",  [testFiles11, testCommon, gtestMainObj])
concurrentCursor  = dllBuildEnv.Program("concurrentCursor",  [testFiles12, testCommon, gtestMainObj])
lobNormal      = dllBuildEnv.Program("lobNormal",  [testFiles13, testCommon, gtestMainObj])
lobAbnormal    = dllBuildEnv.Program("lobAbnormal",  [testFiles14, testCommon, gtestMainObj])

# static compile

decimal.static       = staticBuildEnv.Program("decimal.static",      [testFiles1, testCommon, gtestMainObj])
numberLong.static    = staticBuildEnv.Program("numberLong.static",   [testFiles2, testCommon, gtestMainObj])
turnOncache.static   = staticBuildEnv.Program("turnOncache.static",  [testFiles3, testCommon, gtestMainObj])
restAbnormal.static  = staticBuildEnv.Program("restAbnormal.static", [testFiles4, testCommon, gtestMainObj])
procedure.static     = staticBuildEnv.Program("procedure.static",    [testFiles5, testCommon, gtestMainObj])
socketMutex.static   = staticBuildEnv.Program("socketMutex.static",    [testFiles6, testCommon, gtestMainObj])
index.static         = staticBuildEnv.Program("index.static",    [testFiles7, testCommon, gtestMainObj])
dropCsAndWriteLob.static = staticBuildEnv.Program("dropCsAndWriteLob.static",    [testFiles8, testCommon, gtestMainObj])
concurrentCs.static  = staticBuildEnv.Program("concurrentCs.static",    [testFiles9, testCommon, gtestMainObj])
concurrentCl.static  = staticBuildEnv.Program("concurrentCl.static",    [testFiles10, testCommon, gtestMainObj])
concurrentLob.static     = staticBuildEnv.Program("concurrentLob.static",    [testFiles11, testCommon, gtestMainObj])
concurrentCursor.static  = staticBuildEnv.Program("concurrentCursor.static",    [testFiles12, testCommon, gtestMainObj])
lobNormal.static         = staticBuildEnv.Program("lobNormal.static",  [testFiles13, testCommon, gtestMainObj])
lobAbnormal.static       = staticBuildEnv.Program("lobAbnormal.static",  [testFiles14, testCommon, gtestMainObj])

# dll compile
env.Install( '#/build_test', [   decimal,
                                 numberLong, 
                                 turnOncache,
								 restAbnormal,
								 procedure,
								 socketMutex,
								 index,
								 dropCsAndWriteLob,
								 concurrentCs,
							 	 concurrentCl,
								 concurrentLob,
								 concurrentCursor,
								 lobNormal,
								 lobAbnormal
                              ] )
# static compile
env.Install( '#/build_test', [   decimal.static,
                                 numberLong.static,
                                 turnOncache.static,
         						 restAbnormal.static,
         						 procedure.static,
								 socketMutex.static,
								 index.static,
								 dropCsAndWriteLob.static,
								 concurrentCs.static,
								 concurrentCl.static,
								 concurrentLob.static,
								 concurrentCursor.static,
								 lobNormal.static,
								 lobAbnormal.static
                              ] )

