# 执行结果存储在build_valgrind下的result目录
# 如果部署了环境执行用例的时候，执行用例的命令错误或者因为配置问题导致用例执行失败，可以将needcover和needinstall置为false，可以跳过部署环境步骤，开启valgrind线程执行用例
# 需要执行内存泄露的主机ip地址，逗号隔开
host_address="192.168.20.74,192.168.31.9"
# 执行用例的类型，js和java，逗号隔开
runtype="java,js"
# 需要执行用例所在的目录，可以为相对路径和绝对路径,用逗号隔开，可以填写多个
# 执行单个目录文件夹时，填入/opt/testcase_new/story/js/index，执行整个js目录下的所有用例时，填入/opt/testcase_new/story/js
testcase_dir="../../share/users/yinzhen/trunk/trunk/testcase_new/sdv/js/,/share/users/yinzhen/trunk/trunk/testcase_new/story/js/"
# 需要执行java用例的testng.xml所在目录的路径，可以为绝对路径和相对路径
javapath=/share/users/yinzhen/trunk/trunk/testcase_new/reliability/java
# 需要执行的xml文件
testngxml=testng.xml
# 安装|升级安装|覆盖安装都需要将安装的tar包放入package目录下
# 是否需要覆盖安装SequoiaDB，多台主机之间存在多个不同的集群时需要填此项
needcover=false
# 是否需要升级或安装SequoiaDB
needinstall=false
